name: total_iconify
description: "Complete Iconify icons for flutter"
version: 0.0.1
homepage: https://github.com/dapotatoman/total_iconify

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.3
  vector_graphics: ^1.1.19

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  vector_graphics_compiler: ^1.1.19
  custom_lint: ^0.8.1
